name: updateStationData.yml
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python updateStationData.py

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: auto-update-stationData
          commit-message: 'Auto update stationData'
          title: "Auto update stationData"
          body: "Automated changes from updateStationData.py script run"
          base: master
          draft: false

      - name: Auto-merge Pull Request
        if: steps.create-pr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: 'squash'
